### ISSUE TITLE
Upgrade grpc-go dependency to allow drivers to be written in rust / typescript 

### ISSUE THREAD

**Issue by entropitor** [kubernetes/kubelet#15]
Due to a bug in grpc-go, CSI drivers in typescript / rust weren't working. This has been fixed so now this package needs to update its dependency on grpc-go soon (grpc/grpc-go#2628). It would be even better if this fixed could be backported to older versions of kubernetes

**Comment by nikhita** [comment]
@entropitor I'll close this issue in favor of https://github.com/kubernetes/kubernetes/issues/93320. This repo is a copy of the code in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubelet and any changes that need to be made need to go in the kubernetes/kubernetes repo.

**Comment by entropitor** [comment]
Okay, good to know!
