### ISSUE TITLE
Feature Request: configure CNI in KubeletConfiguration as opposed to choosing based on lexicographic order

### ISSUE THREAD

**Issue by medyagh** [kubernetes/kubelet#25]
in minikube we noticed that during kubeadm init, kuberentes picks up the first alphabetical CNI that could cause some unexpected issues with choosing CNIs

based on this comment from @afbjorklund https://github.com/kubernetes/minikube/issues/10788#issuecomment-797289498

```
If there are multiple CNI configuration files in the directory, the kubelet
uses the configuration file that comes first by name in lexicographic order.
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni
```

would it be possible to have a flag to pass to kubeadm init to specify the CNI explicitly ?

**Comment by medyagh** [comment]
@neolit123 
/sig node
/area kubelet

**Comment by neolit123** [comment]
just to copy my previous comment about this:

> kubeadm allows the users to configure the kubelet via KubeletConfiguration.
AFAIK the field to control this CNI related behavior is missing there, so that is a kubelet issue.

https://github.com/kubernetes/kubeadm/issues/2408

**Comment by neolit123** [comment]
btw, i'm not sure how actively triaged this repository is.
from what i know the main issue tracker for the kubelet remains k/k.

**Comment by medyagh** [comment]
@neolit123  thanks for the head up I will move it there

**Comment by medyagh** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/100309
