### ISSUE TITLE
Pod stuck at every steps of deployment - need to restart kubelet

### ISSUE THREAD

**Issue by 51103220** [kubernetes/kubelet#26]
Hi team,

I'd like to report the current issue of our k8s cluster that we can not deploy/schedule any pods onto any nodes automatically.

We have a cluster including 3 worker nodes and 1 control plane. The Kubernetes version is v1.18.9 and we have been running the cluster normally for months.

Recently, we've encountered the issue of pod getting stuck at every step of lifecycle (scheduling, containerCreating, terminating, ...)  and we had to manually restart the kubelet service step by step to make it move on.

For example, we triggered a Gitlab pipeline which created a new runner pod. 

Try describing the pod we could see it was successfully assigned to a node. However, it get stuck at this step forever (or at least long enough to make Gitlab pipeline timeout)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/8266389/115685594-8d803e00-a382-11eb-878e-7e14b67a9d59.png)

We checked the kubelet logs on the node and found nothing special. Even "kubectl get events" on master returns nothing.

Then we restarted the kubelet with **systemctl restart kubelet** and the pod moved to "ContainerCreating" quickly
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/8266389/115685642-9bce5a00-a382-11eb-963d-373fb98a316e.png)

But it get stuck at this step again and still we had to restart the kubelet on the node. 

The pod went "Running" after the restart.
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/8266389/115685664-a12ba480-a382-11eb-8d75-bb0b28143b2c.png)

Our attempts to identify the cause:

- Try restarting Docker on every machines. It also got stuck and we had to remove all containers from /var/lib/docker/containers
- Try restarting kubelet after Docker restart
- Restarting all the nodes make the cluster back to normal state but this issue happened twice this week. 
- We have launched a virtual NFS server (a k8s deployment) recently and we don't know if this can be the problem.

Could anyone please help me to identify the root cause? Please be free to ask for more information if needed.
Thank you

**Comment by PangQingcheng** [comment]
I had the same problem，Is there any progress? PLEASE

**Comment by PangQingcheng** [comment]
I had the same problem，Is there any progress? PLEASE
