### ISSUE TITLE
kubelet ignores `--container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock` parameters

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubelet#31]
Calling `sudo kubelet -v 1000 --container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock` produces  [this output](https://github.com/kubernetes/kubelet/files/7269881/output.txt).

```
$ kubelet --version
Kubernetes v1.22.3-rc.0.12+2c0e4a232a3c10
$ kubelet --help
...
      --container-runtime string                                 The container runtime to use. Possible values: 'docker', 'remote'. (default "docker")
      --container-runtime-endpoint string                        [Experimental] The endpoint of remote runtime service. Currently unix socket endpoint is supported on Linux, while npipe and tcp endpoints are supported on windows. Note: When using docker as container runtime this specifies the dockershim socket location which kubelet itself creates.  Examples:'unix:///var/run/dockershim.sock', 'npipe:////./pipe/dockershim' (default "unix:///var/run/dockershim.sock")
...
```

My reading of the `kubelet --help` output is, that passing the --container-runtime=remote with --container-runtime-endpoint to kubelet, will convince it to connect to CRI-O.  But instead the log contains
> I1001 22:08:16.666036  319919 plugin.go:68] Docker not connected: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by ehashman** [comment]
Hello,

This is a mirror repo and is not monitored: https://github.com/kubernetes/kubelet#where-does-it-come-from

Please file issues against https://github.com/kubernetes/kubernetes/issues

/close
