### ISSUE TITLE
add option to delete the iptables, created by kubelet

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubelet#32]
`kubeadm reset` does not delete the iptables/ipvs/ipset entries, created by `kubeadm init`.  Part of the entries are created by kube-proxy and can be cleaned by `kube-proxy --cleanup`.  Others are created by kubelet.  See also https://github.com/kubernetes/kubeadm/issues/2587 .

* add  a method to kubelet to delete all iptables/ipvs/ipset entries created by it, so that `kubeadm reset` can revert the effect of `kubeadm init`.

**Comment by ehashman** [comment]
Hello,

This is a mirror repo and is not monitored: https://github.com/kubernetes/kubelet#where-does-it-come-from

Please file issues against https://github.com/kubernetes/kubernetes/issues

/close
