### ISSUE TITLE
Use internal cluster registry to pull image

### ISSUE THREAD

**Issue by fatihdestegul** [kubernetes/kubelet#33]
Hi community,

Not sure if this is the right place to raise this idea/question but will give it a try.

**Problem**
- I have  3 multi-node cluster on prem which doesn't have internet access. (Each of clusters configs are federated by GitOps approaches.)
- I have an internal registry in each cluster. (1 for each, 3 in total.) Registry is serving a pod. (e.g. [Harbor](https://goharbor.io/docs/2.3.0/install-config/harbor-ha-helm/))

**Question/Idea**
In a federated environment each cluster has a different domain. (e.g. myregistry-1.com, myregistry-2.com, myregistry-3.com) Therefore, each registries have different FQDNs. To deploy the same applications into 3 different clusters/regions, I need to change image FQDNs accordingly.

Is it possible to have a common DNS, such as myregistry.local for all clusters so that kubelet will be able to download images locally from local registry, which is basically a pod.. 

Ps: This is something different than configuring a local registry, because my registry runs as a pod and kubelet doesn't know anything about it...

**Comment by ehashman** [comment]
Hello,

This is a mirror repo and is not monitored: https://github.com/kubernetes/kubelet#where-does-it-come-from

Please file issues against https://github.com/kubernetes/kubernetes/issues

/close
