### ISSUE TITLE
Kubelet /stats/summary not working in EKS

### ISSUE THREAD

**Issue by Nimmsy** [kubernetes/kubelet#34]
Hi,

Kubelet endpoint is not working in the EKS setup. kubelet is listening in port 10250 but when the 
endpoint ( http://x.x.x.x:10250/stats/summary ) is accessed from python code it throws error - **Failed to establish a new connection: [Errno 111] Connection refused')**

When the same endpoint is accessed from the terminal - getting success but no data returned - 
PFA
![Screenshot from 2021-10-27 18-05-08](https://user-images.githubusercontent.com/93110847/139066544-6d05a3c9-8e5b-4821-a2c8-e1e67bcfbb04.png)

Any help would be much appreciated.

Regards,
NImmsy

**Comment by ehashman** [comment]
Hello,

This is a mirror repo and is not monitored: https://github.com/kubernetes/kubelet#where-does-it-come-from

Please contact EKS support for any issues you're encountering with EKS, this is a community-run project repo.

/close
