### ISSUE TITLE
Failed to create existing container: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podxx.slice/crio-xx.scope

### ISSUE THREAD

**Issue by haitang5445** [kubernetes/kubelet#35]
kubelet 1.20.12
crio 1.20.5 
#systemctl status kubelet -l
Nov 10 11:50:23 k8sm01 kubelet[29772]: E1110 11:50:23.784299   29772 manager.go:1123] Failed to create existing container: /kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podd6ac557d7d2316fa37c7fde53ab78837.slice/crio-93632fe92af9f256ed6eb70b770e1ace809e413a2c6a09c26411d7751a5a8dd1.scope: Error finding container 93632fe92af9f256ed6eb70b770e1ace809e413a2c6a09c26411d7751a5a8dd1: Status 404 returned error &{%!s(*http.body=&{0xc000eca4e0 <nil> <nil> false false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x7759c0) %!s(func() error=0x775940)}

**Comment by ehashman** [comment]
Hello,

This is a mirror repo and is not monitored: https://github.com/kubernetes/kubelet#where-does-it-come-from

Please file issues against https://github.com/kubernetes/kubernetes/issues

/close
