### ISSUE TITLE
kubelet won't start

### ISSUE THREAD

**Issue by richyguo** [kubernetes/kubelet#4]
[root@ip-10-247-239-16 ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-09-10 16:17:59 EDT; 5s ago
     Docs: https://kubernetes.io/docs/
  Process: 8695 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=255)
 Main PID: 8695 (code=exited, status=255)

Sep 10 16:17:59 ip-10-247-239-16.awscloud.cms.local systemd[1]: Unit kubelet.service entered failed state.
Sep 10 16:17:59 ip-10-247-239-16.awscloud.cms.local systemd[1]: kubelet.service failed.

**Comment by richyguo** [comment]
I am trying to setup kubernetes in AWS EC2 instances. I am using RH7.7. Kubelet won't stay up. Can someone help, please?

**Comment by zxx287856774** [comment]
journalctl -xe  see kubelet start describe logs

**Comment by richyguo** [comment]
Thanks, I think it is rather kubeadm issue.

**Comment by Ramadapu** [comment]
Faced the same issue, tried "sudo swapoff -a" and it worked.
