### ISSUE TITLE
windows pod error while adding to cni network: error while ProvisionEndpoint: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by yuwei1chen** [kubernetes/kubelet#40]
## Expected Behavior
We want to run docker windows hyperv isolation mode in kubernetes.
Both Windows hyperv isolation mode and process isolation mode container pod in kubernetes is started correctly with a pod ip and right network configuration.

## Current Behavior
Everything works fine for windows isolation mode pods in kubernetes.But for windows hyperv isolation mode pods, they have no pod ip and keeps restarting. 
below is what I got from "kubelet get pod -o wide", we can see that in IP column is "<none>". And it keeps restarting and have restarted 51 times:
`hyperv-0   0/1     CrashLoopBackOff   51         110m   <none>          jf53120cp-hv `

In kubelet log, we see:
`E0315 00:04:48.592295   11324 cni.go:366] Error adding hyperv-0/ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23 to network flannel/flannel.4096: error while ProvisionEndpoint(ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23_flannel.4096,D3CBB652-3DCC-486F-BBB5-690D54C96F18,ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23): Cannot create a file when that file already exists.
E0315 00:04:48.592295   11324 cni_windows.go:59] error while adding to cni network: error while ProvisionEndpoint(ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23_flannel.4096,D3CBB652-3DCC-486F-BBB5-690D54C96F18,ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23): Cannot create a file when that file already exists.`

The only different in 2 isolation mode pods is the annotation "experimental.windows.kubernetes.io/isolation-type: hyperv", which is to tell kubelet which windows container isolation mode to use.

## Context
We are trying the Windows hyperv isolation mode feature gate in kubernetes. Process isolation mode works fine, but pods cannot get pod ip when started with isolation mode.

## Your Environment
* Flannel version: flannel:v0.13.0-nanoserver
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.4.13
* Kubernetes version (if used): 1.20.2
* Operating System and version: Windows Server 2019
* Link to your project (optional):

**Comment by kundan2707** [comment]
@yuwei1chen  can you check if file already existing and its permission?
