### ISSUE TITLE
kubelet fails to be restarted when the NFS server is offline.

### ISSUE THREAD

**Issue by llchry** [kubernetes/kubelet#43]
Hi team,

I'd like to report the current issue of our k8s cluster .

Prerequisites
1. Start the NFS server on machine1.
2. Mount the NFS shared disk of machine1 to machine2, `mount -o nfsvers=4,rw,tcp,retry=0,timeo=${mount_timeo:-6000} 172.10.10.10:/opt/backup/ /opt/backup/elasticsearch/repo`
3. Stop the NFS server on machine 1.
4. Restart kubelet on machine 2.

The Kubernetes version is v1.25.3. In this case, access to the shared disk on machine 2 is blockedwhich I guess is why kubelet fails to start. Therefore, I suggest that you use the OS library to access system resources. Do you add a timeout setting to avoid startup failure in this case?

**Comment by tamilselvan1102** [comment]
Most operations on nfs mountpoint will hang if the connection to nfs server is lost.
