### ISSUE TITLE
why doesn't have a api interface of container list?

### ISSUE THREAD

**Issue by yinchengjian** [kubernetes/kubelet#44]
why doesn't have a api interface of container list?

we don't get current status of containers

**Comment by tamilselvan1102** [comment]
For container state and tracking, ref  [here ](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-states)

**Comment by tamilselvan1102** [comment]
@yinchengjian 
if you are satisfied, please close the issue
