### ISSUE TITLE
kubelet service not running on workernode  (eks  setup)

### ISSUE THREAD

**Issue by Dabbeeru** [kubernetes/kubelet#6]
systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-01-01 20:09:05 UTC; 2s ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 29398 ExecStart=/usr/bin/kubelet --cloud-provider aws --config /etc/kubernetes/kubelet/kubelet-config.json --allow-privileged=true --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime docker --network-plugin cni $KUBELET_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=255)
  Process: 29397 ExecStartPre=/sbin/iptables -P FORWARD ACCEPT (code=exited, status=0/SUCCESS)
 Main PID: 29398 (code=exited, status=255)

Jan 01 20:09:05 ip-192-168-101-196.ec2.internal systemd[1]: Unit kubelet.service entered failed state.
Jan 01 20:09:05 ip-192-168-101-196.ec2.internal systemd[1]: kubelet.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@ip-192-168-101-196 /]# journalctl -xe see kubelet start describe logs
Failed to add match 'see': Invalid argument
Failed to add filters: Invalid argument

note:- on api server iam running kubectl get nodes (no resource found error)

Please assist me how to fix the issue.

**Comment by cmonty14** [comment]
Hi,
I'm facing the same issue starting kubelet on FCOS (Fedora CoreOS).
```
[core@vm191-fcos ~]$ systemctl status kubelet
* kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           `-10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-01-24 14:37:07 UTC; 2s ago
     Docs: https://kubernetes.io/docs/
  Process: 297465 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=255/EXCEPTION)
 Main PID: 297465 (code=exited, status=255/EXCEPTION)
```

Where can I find additional information why service fails to start?

**Comment by Dabbeeru** [comment]
Hi

**Comment by Dabbeeru** [comment]
worker node :-
           ec2-user# cd /opt
            opt# vi script.sh
        #sudo vi script.sh
         #sudo chmod +x /opt/script.sh
         #vi script.sh
      #!/usr/bin/env bash
sudo /etc/eks/bootstrap.sh --apiserver-endpoint <your endpoint>
--b64-cluster-ca <yourca> <yourclustername>

Note :-Please add your eks cluster apiend_point _url and
certificate_manager_url and eks_ cluster_name

**Comment by cmonty14** [comment]
Is my assumption correct, that I can enter IP of master node for <apiserver-endpoint>?

**Comment by cmonty14** [comment]
There's no directory `/etc/eks/` on any server running Fedora CoreOS.

**Comment by MunawarRaza** [comment]
hi i have been facing an issue. Issue is that when i start a container in kubernetes using yml file with image centos/ubuntu it goes to CrashLoopBackOff. when i create container using nginx image in yml file it works fine. Can you guide me please?

**Comment by MunawarRaza** [comment]
kubelete container is also not running at worker node
